force-app/main/default/objects/TwilioSMS__c/TwilioSMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TwilioSMS</label>
</CustomObject>

force-app/main/default/objects/TwilioSMS__c/fields/AccountSid__c.field-meta.xml
<CustomField>
    <fullName>AccountSid__c</fullName>
    <label>AccountSid</label>
    <length>34</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwilioSMS__c/fields/FromNumber__c.field-meta.xml
<CustomField>
    <fullName>FromNumber__c</fullName>
    <inlineHelpText>E164 Format, e.g. +1....</inlineHelpText>
    <label>FromNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMSHandler.cls
public class SMSHandler {
	
    @AuraEnabled
    public static Boolean sendSMS(String bodyString, Id caseId) {
        TwilioSMS__c smsSettings = TwilioSMS__c.getOrgDefaults();


        Case c = [Select Id, Contact.Phone from Case where Id =:caseId limit 1][0];
        

        HttpRequest req = new HttpRequest();
        
        req.setEndpoint('callout:TwilioSMS/' + smsSettings.AccountSid__c + '/Messages.json');
        req.setMethod('POST');
        
        String body = '';
        body += 'From=' + (EncodingUtil.urlEncode(smsSettings.FromNumber__c, 'UTF-8'));
        body += '&Body=' +(EncodingUtil.urlEncode(bodyString, 'UTF-8'));
        body += '&To=' +(EncodingUtil.urlEncode(c.Contact.Phone, 'UTF-8'));
        
            
        req.setBody(body);
        Http http = new Http();
        HTTPResponse res = http.send(req);

        return res.getStatusCode() == 201;
    }
}